### ISSUE TITLE
[Bug] 任何note标签都会自带modern样式

### ISSUE THREAD

**Issue by MskTmi** [everfu/hexo-solitude-tag#7]
任何note标签都会自带modern样式，导致flat样式无法正常显示

无设定样式：
![image](https://github.com/user-attachments/assets/36844920-de58-4a0d-8626-e1703f6634d9)

设定flat样式：
![image](https://github.com/user-attachments/assets/29486b61-b372-443e-952d-b44ecc4d892d)

**Comment by MskTmi** [comment]
顺便建议一下样式，只是个人习惯了butterfly，总感觉现在标签有点过宽，这是我目前修改的样式
```css
.article-container .note p {
    font-size: 0.7rem;
    line-height: 1.7;
    font-weight: 400;
    margin: 0;
    text-align: left;
    letter-spacing: 0.6px;
}

.note:not(.no-icon) {
    padding-left: 0.6rem;
}
```
![image](https://github.com/user-attachments/assets/b361a2db-b0b5-4f5b-8685-1bb65d8267ec)
